name: flutterd
description: Opinionated library for building Flutter applications.
version: 0.0.2

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.1.0
  typed_data: ^1.4.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  intl: ^0.20.2
  flutterd_logging_wrapper: 
    # path: ../flutterd_logging_wrapper
    git:
      url: https://github.com/thzero/flutterd_logging_wrapper
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  shared_preferences: ^2.3.5
  http: ^1.2.2  #  HTTP Helper. From https://pub.dev/packages/http
  sprintf: ^7.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_i18n: ^0.36.3
  flex_color_scheme: ^8.3.0   
  flutter_settings_ui: ^3.0.1
  tap_debouncer: ^2.2.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1 
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  flutter_titled_container: 
    # path: ../flutter_titled_container
    git:
      url: https://github.com/thzero/flutter_titled_container
      ref: dev
  
  flutter_localizations: # add this line
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.8.0

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
