name: flutterd
description: Opinionated library for building Flutter applications.
version: 0.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.0.0
  typed_data: ^1.3.1   #  Helpers for Byte Buffers. From https://pub.dev/packages/typed_data
  equatable: ^2.0.5  #  Object Equality Helper. From https://pub.dev/packages/equatable
  uuid: ^3.0.6
  loggerx: ^1.3.5
  flutterd_logging_wrapper: 
    # path: ../flutterd_logging_wrapper
    git:
      url: https://github.com/thzero/flutterd_logging_wrapper
  path_provider: ^2.0.11
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15
  http: ^0.13.5  #  HTTP Helper. From https://pub.dev/packages/http
  sprintf: ^6.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  flutter_i18n: ^0.32.4
  flex_color_scheme: ^6.0.0
  flutter_settings_ui: ^2.0.1
  tap_debouncer: ^2.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  flutter_colorpicker: ^1.0.3
  
  flutter_localizations: # add this line
    sdk: flutter 
  intl: ^0.17.0   
  country_pickers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
